
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.MOODLE_SSH_PRIVATE_KEY }}
    - name: Deploy Moodle
      run: |
        rsync -avz --exclude '.git*' --exclude 'config.php' --exclude 'moodledata' . root@khaledbahloul.org:/var/www/html/mymoodles/moodle
        ssh root@khaledbahloul.org 'php /var/www/html/mymoodles/moodle/admin/cli/upgrade.php --non-interactive'
